import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
function moduleBody(file) {
  const source = read(file)
    .replace(/^import .+ from ['"].+['"];\r?\n/gm, '')
    .replace(/^export (?=(?:const|function|class)\b)/gm, '');
  if (/^\s*(?:import|export)\s/m.test(source)) throw new Error(`Unsupported module syntax: ${file}`);
  return source;
}

// Keep module scopes separate. This small explicit bundle needs no npm packages,
// eval, network requests, or file:// module access at runtime.
export function renderStandalone() {
  const payload = JSON.stringify({ cards: JSON.parse(read('data/cards.json')), factions: JSON.parse(read('data/factions.json')) }).replace(/</g, '\\u003c');
  const script = `(() => {\n'use strict';\nglobalThis.KOPRULU_DATA = ${payload};
const engineModule = (() => {
${moduleBody('src/engine.js')}
return { createEngine, CELLS, distance, RuleError };
})();
const botModule = (() => {
const { distance, RuleError } = engineModule;
${moduleBody('src/bot.js')}
return { chooseBotAction };
})();
const savesModule = (() => {
${moduleBody('src/saves.js')}
return { SAVE_KEY, MAX_SAVE_BYTES, encodeSave, decodeSave };
})();
(() => {
const { createEngine, CELLS, distance } = engineModule;
const { chooseBotAction } = botModule;
const { SAVE_KEY, MAX_SAVE_BYTES, encodeSave, decodeSave } = savesModule;
${moduleBody('src/app.js')}
})();
})();`;
  return '<!-- Generated by node scripts/build-desktop.mjs. Edit src/ and index.html, then rebuild. -->\n' + read('index.html')
    .replace(/<!-- file-entry:start -->[\s\S]*?<!-- file-entry:end -->/, '')
    .replace('<link rel="stylesheet" href="src/style.css">', () => `<style>\n${read('src/style.css')}\n</style>`)
    .replace('<script type="module" src="src/app.js"></script>', () => `<script>\n${script.replace(/<\/script/gi, '<\\/script')}\n</script>`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  const output = renderStandalone();
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(path.join(root, 'Play.html')) || read('Play.html') !== output) {
      console.error('Play.html is out of date. Run npm run build:desktop.'); process.exitCode = 1;
    } else console.log('Play.html matches the current source.');
  } else {
    fs.writeFileSync(path.join(root, 'Play.html'), output);
    console.log(`Play.html: ${Buffer.byteLength(output)} bytes. Open it from the extracted project folder.`);
  }
}
